# 行政書士法人ふらっと法務事務所 入札サポート専門サイト

title: "行政書士法人ふらっと法務事務所"
description: "入札サポート専門サイト - 代表 塩澤康幸があなたの入札を成功に導きます"
baseurl: ""
url: "https://flatto-legal-site.netlify.app"

# 会社情報
company:
  name: "行政書士法人ふらっと法務事務所"
  representative: "代表 行政書士 塩澤康幸"
  phone: "046-272-3357"
  email: "mail@flat-legal.com"
  address: "〒242-0006 神奈川県大和市南林間6丁目4番26号 1F"
  hours: "電話受付 平日9時～17時 / メール24時間受付"
  station: "小田急線南林間駅徒歩7分"
  established: "2021年4月9日"
  staff: "6名体制"
  privacy_mark: "プライバシーマーク取得（2024年9月19日）"

# SEO設定
author: "行政書士法人ふらっと法務事務所"
twitter:
  username: flatto_legal
  card: summary_large_image

# ビルド設定
markdown: kramdown
highlighter: rouge
permalink: pretty
encoding: utf-8
strict_front_matter: false
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# プラグイン
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# コレクション設定
collections:
  pages:
    output: true
    permalink: /:name/

# 除外ファイル
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - CHANGELOG.md
  - "*.tmp"
  - "*.bak"

# 含めるファイル
include:
  - _pages
  - search-index.json
  - .htaccess

# デフォルト設定
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"

# Sass設定
sass:
  style: compressed
  sass_dir: _sass

# 開発設定
livereload: true
incremental: true

# アナリティクス設定
# Google Analytics 4 (GA4) - 測定IDを設定してください
# 例: google_analytics: "G-XXXXXXXXXX"
google_analytics: ""

# Google Tag Manager - コンテナIDを設定してください  
# 例: google_tag_manager: "GTM-XXXXXXX"
google_tag_manager: ""

# Google Search Console - 所有権確認用メタタグ
# 例: google_site_verification: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
google_site_verification: ""

