# 行政書士法人ふらっと法務事務所 入札サポート専門サイト

title: "行政書士法人ふらっと法務事務所"
description: "入札サポート専門サイト - 代表 塩澤康幸があなたの入札を成功に導きます"
baseurl: ""
url: "https://nyusatsu-map.com"

# 会社情報
company:
  name: "行政書士法人ふらっと法務事務所"
  representative: "代表 行政書士 塩澤康幸"
  phone: "046-272-3357"
  email: "mail@flat-legal.com"
  address: "〒242-0006 神奈川県大和市南林間6丁目4番26号 1F"
  hours: "電話受付 平日9時～17時 / メール24時間受付"
  station: "小田急線南林間駅徒歩7分"
  established: "2021年4月9日"
  staff: "6名体制"
  privacy_mark: "プライバシーマーク取得（2024年9月19日）"

# SEO設定
author: "行政書士法人ふらっと法務事務所"
twitter:
  username: flatto_legal
  card: summary_large_image

# Open Graph / Social Media設定
social:
  name: "入札マップ"
  links:
    - "https://twitter.com/flatto_legal"

# URL設定
permalink: /blog/:title/

# プラグイン設定
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

# デフォルト設定
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/images/og-image.webp"
      sitemap: true
  - scope:
      path: "_posts"
      type: "posts"
    values:
      image: "/assets/images/blog/default-blog-image.jpg"
      sitemap: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      sitemap: true
  - scope:
      path: ""
    values:
      layout: "default"
      sitemap: true

# ビルド設定
markdown: kramdown
highlighter: rouge
permalink: pretty
encoding: utf-8
strict_front_matter: false
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# プラグイン
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass設定
sass:
  style: compressed
  sass_dir: _sass

# 開発設定
livereload: true
incremental: true

# アナリティクス設定
# Google Analytics 4 (GA4) - 測定IDを設定
google_analytics: "G-B9ZDWJ2ZEP"

# Google Tag Manager - コンテナIDを設定してください  
# 例: google_tag_manager: "GTM-XXXXXXX"
google_tag_manager: ""

# Google Search Console - 所有権確認用メタタグ
# 例: google_site_verification: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
google_site_verification: ""


# Minor change to trigger rebuild - 2025-08-25
# Force sitemap regeneration
sitemap_regenerate: true


# パフォーマンス最適化設定
sass:
  style: compressed  # CSS圧縮を有効化
  sourcemap: never   # ソースマップを無効化（本番環境）

# ビルド最適化
incremental: true    # インクリメンタルビルドを有効化
profile: false       # プロファイリングを無効化（本番環境）

# 除外設定（ビルド時間短縮）
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - README.md
  - LICENSE
  - CHANGELOG.md
  - assets/css/main-backup.scss
  - assets/css/main-optimized.scss

# キャッシュ設定
keep_files:
  - .git
  - .svn

# 圧縮設定
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# 画像最適化設定
picture:
  source: "assets/images"
  output: "assets/images/optimized"
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.5, 2]
      source_lossless: webp
      source_lossy: webp
      fallback_format: original
      fallback_presets:
        webp: 85
        jpg: 75
        png: 65

