[build]
  base = ""
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.0.2"

[[redirects]]
  from = "/old-site/*"
  to = "/:splat"
  status = 301

