# Netlify設定ファイル - 安全なパフォーマンス最適化

# ビルド設定
[build]
  base = ""
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.0.2"

# セキュリティヘッダー設定
[[headers]]
  for = "/*"
  [headers.values]
    # セキュリティヘッダー
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # 基本キャッシュ設定（HTMLファイル用）
    Cache-Control = "public, max-age=3600"

# 静的アセットのキャッシュ設定
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 画像ファイルのキャッシュ設定
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTMLファイルのキャッシュ設定
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# JavaScript/CSSファイルの設定
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# JSON ファイル設定
[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/json; charset=utf-8"

# 正常なリダイレクト設定
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/old-site/*"
  to = "/:splat"
  status = 301

# 注意: 問題のあったワイルドカード404リダイレクトは除外
# [[redirects]]
#   from = "/*"
#   to = "/404.html"
#   status = 404


# ドメインリダイレクト設定
# Netlifyサブドメインから正規ドメインへの301リダイレクト
[[redirects]]
  from = "https://flatto-legal-site.netlify.app/*"
  to = "https://nyusatsu-map.com/:splat"
  status = 301
  force = true

# HTTPからHTTPSへのリダイレクト（念のため）
[[redirects]]
  from = "http://nyusatsu-map.com/*"
  to = "https://nyusatsu-map.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.nyusatsu-map.com/*"
  to = "https://nyusatsu-map.com/:splat"
  status = 301
  force = true

