[build]
  base = "jekyll-site"
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

