# ふらっと法務事務所 入札サポート専門サイト - Jekyll設定

# サイト情報
title: ふらっと法務事務所 入札サポート専門サイト
email: mail@flat-legal.com
description: >-
  ふらっと法務事務所の入札サポート専門サイトです。入札参加のノウハウや成功事例、
  サービス内容などをご紹介しています。
baseurl: "/flatto-legal-site" # GitHub Pagesのサブディレクトリ
url: "https://yasuyuki-shiozawa.github.io" # サイトのベースURL
logo: /assets/images/logo.png

# 会社情報
company:
  name: 行政書士法人ふらっと法務事務所
  address: 〒242-0006 神奈川県大和市南林間6丁目4番26号
  tel: 046-272-3357
  hours: 平日 9:00〜18:00

# ビルド設定
markdown: kramdown
permalink: pretty
sass:
  style: compressed

# コレクション設定
collections:
  pages:
    output: true
    permalink: /:basename/

# デフォルト設定
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

# プラグイン
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# 除外ファイル
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - README.md

# インクルードディレクトリ
include:
  - _pages

# 言語設定
lang: ja
